#!/bin/bash

# CONFIG #
# PATHS without tailin slash
#PIVATE_DIR='private/path/to/dir/'
#PUBLIC_DIR='DIR/ON/URL'
PRIVATE_DIR='sites/annttu.fi/www/t'
PUBLIC_DIR='t'
DOMAIN='annttu.fi'

##################
##################
##################
# Some functions

chr() {
  num=$1
  [ $1 -gt 90 ] && [ $1 -lt 97 ] && num=$(($1+7))
  printf \\$(printf '%03o' $num)
}

rd() {
  b=`echo $RANDOM |cut -c 1-2`
  [ $b -gt 20 ] && return 0
  return 1
}

if [ "$1" == "-q" ]
then
	QUIET=1
	FILE="$2"
else
	QUIET=0
	FILE="$1"
fi

SUFFIX="`echo $FILE |sed -e 's/.*\.//'`"

# create short pseudo random string
AA=''
for i in `date +"%H %m %d %y %S %M"`
do
	if `rd`
	then
		let "i=10#$i"
		b=$(($i+65))
		b="`chr $b`"
		AA="${AA}${b}"
	else
		let "i=10#$i"
		AA="${AA}$((i/10))"
	fi
done
b=`echo $RANDOM |cut -c 1-2`
[ $b -gt 122 ] && b=$(($b / 122))
[ $b -lt 64 ] && b=$(($b+64))
b=`chr $b`
AA=${AA}${b}
#echo $AA

scp "$FILE" $DOMAIN:$PRIVATE_DIR/${AA}.${SUFFIX} #> /dev/null 2> /dev/null
if [ "$?" == "0" ]
then
	if [ "$QUIET" == "0" ]
	then
		echo -e "\n# GOTO:\thttp://$DOMAIN/$PUBLIC_DIR/${AA}.${SUFFIX}\n"
	else
		echo "http://$DOMAIN/$PUBLIC_DIR/${AA}.${SUFFIX}"
	fi
else
	if [ "$QUIET" == "0" ]
	then
		echo "Ei voittoa"
	fi
fi
